name: univalle_news
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  cloud_firestore: ^4.12.1
  firebase_auth: ^4.12.0
  firebase_core: ^2.20.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_bloc: ^7.2.2 # Utiliza la versi칩n m치s reciente de flutter_bloc
  bloc: ^7.0.1 # Utiliza la versi칩n m치s reciente de bloc

flutter:
  assets:
    - assets/
  uses-material-design: true
